--askhsh 2a(checked)
CREATE OR REPLACE FUNCTION CUSTOMEREXIST(AT_ IN VARCHAR2)
RETURN NUMBER IS
EXIST VARCHAR2(20 BYTE);
CURSOR A_T IS
SELECT AT FROM customer WHERE AT=AT_;
BEGIN 
OPEN A_T;
FETCH A_T INTO EXIST;
IF A_T%FOUND THEN
RETURN 0;
ELSE 
RETURN -1;
END IF;
CLOSE A_T;
END;

--askhsh 2b (checked)
CREATE OR REPLACE FUNCTION CUSTOMERINBOOKING(AT_ IN VARCHAR2)
RETURN NUMBER IS
CURSOR AT_CURSOR IS
SELECT AT FROM CUSTOMER WHERE AT=AT_;
AT_VAR AT_CURSOR%ROWTYPE;
CURSOR IN_BOOKING IS 
SELECT BOOK_ID FROM BOOKING WHERE AT=AT_ AND BOOK_OUT_DATE<CURRENT_TIMESTAMP;
BOOK_ID VARCHAR2(20 BYTE);
C NUMBER;
BEGIN 
OPEN AT_CURSOR;
FETCH AT_CURSOR INTO AT_VAR;
IF AT_CURSOR%FOUND THEN
OPEN IN_BOOKING;
IF IN_BOOKING%FOUND THEN
RETURN BOOK_ID;
CLOSE IN_BOOKING;
END IF;
ELSE 
C:=CUSTOMEREXIST(AT_);
DBMS_OUTPUT.put_line(C);
END IF;
END;


